books/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from books import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^add_book/$', views.add_book, name='add_book'),
	url(r'^edit_book/(?P<book_id>\d+)/$', views.edit_book, name='edit_book'),
	url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
	url(r'^search/$', views.search, name='search'),
	url(r'^make_request/(?P<id>\d+)/$', views.make_request, name='make_request'),
)

urlpatterns += staticfiles_urlpatterns()

bookzilla/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from bookzilla import views

urlpatterns = patterns('',
	# index page
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^admin/', include(admin.site.urls)),
    
    # the users module
    url(r'^users/', include('users.urls', namespace='users')),
    # courier module
    url(r'^courier/', include('courier.urls', namespace='courier')),
)

urlpatterns += staticfiles_urlpatterns()

courier/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from courier import views

urlpatterns = patterns('',
	url(r'^login/$', views.login, name='login'),
	url(r'^home/$', views.home, name='home'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^advance/(?P<req_id>\d+)/$', views.advance_request, name='advance'),
)

urlpatterns += staticfiles_urlpatterns()

courier/models.py
from django.db import models

# Create your models here.

courier/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='username')
	password = forms.CharField(widget=forms.PasswordInput())

courier/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from django.contrib.auth import authenticate
from django.contrib.auth import login as djlogin
from django.contrib.auth import logout as djlogout

from .forms import LoginForm

from .misc import is_member

from bookrequests.models import BookRequest

def login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username=username, password=password)

			if user is not None and is_member(user, 'Couriers'):
				djlogin(request, user)
				return HttpResponseRedirect(reverse('courier:home'))
			else:
				messages.error(request,
		     	'The username or password you entered is incorrect')

	form = LoginForm()
	return render(request, 'courier/index.html',
				{
					'form': form
				})

@login_required(login_url='/courier/login')
def home(request):
	requests = BookRequest.objects.all().exclude(status=BookRequest.REQUEST_REJECTED).exclude(status=BookRequest.REQUEST_MADE)

	return render(request, 'courier/home.html',
				{
					'requests' : requests
				})

@login_required(login_url='/courier/login')
def logout(request):
	djlogout(request)
	return HttpResponseRedirect(reverse('courier:login'))

@login_required(login_url='/courier/login')
def advance_request(request, req_id):
	req = get_object_or_404(BookRequest, pk=req_id)
	req.status = req.next_status()
	req.save()
	
	return HttpResponseRedirect(reverse('courier:home'))

courier/templates/courier_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookzilla</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="#">Bookzilla</a>
        </div>

      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
      <div class="col-md-9">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}">{{ msg }}</div>  
          {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
      </div>
        
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

courier/templates/courier_home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookzilla</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="#">Bookzilla</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'courier:logout' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">
      <div class="starter-template">

      <div class="">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}">{{ msg }}</div>  
          {% endfor %}
        {% endif %}

        {% block content %} 
        {% endblock %}
      </div>
        
      </div>
    </div><!-- /.container -->
    

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>