bookrequests/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from bookrequests import views

urlpatterns = patterns('',
	url(r'^lent/$', views.lent_index, name='lent'),
	url(r'^borrowed/$', views.borrowed_index, name='borrowed'),
	url(r'^accept/(?P<id>\d+)/$', views.accept, name='accept'),
	url(r'^reject/(?P<id>\d+)/$', views.reject, name='reject'),
	url(r'^return/(?P<id>\d+)/$', views.return_book, name='return'),
)

urlpatterns += staticfiles_urlpatterns()

books/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from books import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^add_book/$', views.add_book, name='add_book'),
	url(r'^edit_book/(?P<book_id>\d+)/$', views.edit_book, name='edit_book'),
	url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
	url(r'^search/$', views.search, name='search'),
	url(r'^make_request/(?P<id>\d+)/$', views.make_request, name='make_request'),
)

urlpatterns += staticfiles_urlpatterns()

bookzilla/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from bookzilla import views

urlpatterns = patterns('',
	# index page
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^admin/', include(admin.site.urls)),
    
    # the users module
    url(r'^users/', include('users.urls', namespace='users')),
    # courier module
    url(r'^courier/', include('courier.urls', namespace='courier')),
)

urlpatterns += staticfiles_urlpatterns()

courier/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from courier import views

urlpatterns = patterns('',
	url(r'^login/$', views.login, name='login'),
	url(r'^home/$', views.home, name='home'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^advance/(?P<req_id>\d+)/$', views.advance_request, name='advance'),
)

urlpatterns += staticfiles_urlpatterns()

bookrequests/models.py
from django.db import models

from django.contrib.auth.models import User

from books.models import Book

class BookRequest(models.Model):
	REQUEST_MADE = 0

	REQUEST_ACCEPTED = 1
	REQUEST_REJECTED = 2

	WITH_COURIER_TO_BORROWER = 3

	WITH_BORROWER = 4
	DONE_READING = 5

	WITH_COURIER_TO_OWNER = 6
	RETURNED = 7
	

	STATUS_CHOICES = (
		(REQUEST_MADE, 'request pending'),
		(REQUEST_ACCEPTED, 'request accepted' ),
		(REQUEST_REJECTED, 'request rejected' ),
		(WITH_COURIER_TO_BORROWER, 'being delivered to borrower' ),
		(WITH_BORROWER, 'with borrower' ),
		(DONE_READING, 'done reading' ),
		(WITH_COURIER_TO_OWNER, 'being delivered to owner' ),
		(RETURNED, 'returned' ),
	)		

	book = models.ForeignKey(Book)
	borrower = models.ForeignKey(User)
	status = models.IntegerField(default=0, choices=STATUS_CHOICES)

	def __str__(self):
		return str(self.borrower) + \
				" requested " + str(self.book) + " from " + \
				 str(self.book.owner)

	def next_status(self):
		next_statuses = {
			# set manually, dont use this function
			# to advance a pending request
			self.REQUEST_MADE: self.REQUEST_MADE,

			self.REQUEST_ACCEPTED: self.WITH_COURIER_TO_BORROWER,

			self.REQUEST_REJECTED: self.REQUEST_REJECTED,

			self.WITH_COURIER_TO_BORROWER: self.WITH_BORROWER,

			self.WITH_BORROWER: self.DONE_READING,

			self.DONE_READING: self.WITH_COURIER_TO_OWNER,

			self.WITH_COURIER_TO_OWNER: self.RETURNED,

			self.RETURNED: self.RETURNED,
		}

		return next_statuses[self.status]

bookrequests/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse

# models
from books.models import Book
from .models import BookRequest

@login_required
def lent_index(request):
	user = request.user
	requests = BookRequest.objects.all().filter(book__owner=user)

	# get requests where the owner is 'user'
	# my_lent = (r for r in requests if r.book.owner == user)

	return render(request,
				'bookrequests/lent_index.html', 
				{
					'requests': requests
				})

@login_required
def borrowed_index(request):
	user = request.user
	requests = BookRequest.objects.all().filter(borrower=user)

	# get requests where the borrower is 'user'
	# my_borrowed = (r for r in requests 
	# 					if r.borrower == user)

	return render(request,
				'bookrequests/borrowed_index.html', 
				{
					'requests': requests
				})

@login_required
def accept(request, id):
	req = get_object_or_404(BookRequest, pk=id)
	
	req.status = BookRequest.REQUEST_ACCEPTED
	req.save()

	return HttpResponseRedirect(reverse('users:requests:lent'))

@login_required
def reject(request, id):
	req = get_object_or_404(BookRequest, pk=id)	

	req.status = BookRequest.REQUEST_REJECTED
	req.save()
	
	return HttpResponseRedirect(reverse('users:requests:lent'))	

@login_required
def return_book(request, id):
	req = get_object_or_404(BookRequest, pk=id)	

	req.status = req.next_status()
	req.save()
	
	return HttpResponseRedirect(reverse('users:requests:borrowed'))	

bookrequests/templates/bookrequests/_request_tabs.html
<ul class="nav nav-tabs" id="tabs">
  <li class="active"><a href="#pending" data-toggle="tab">Pending</a></li>
  <li ><a href="#completed" data-toggle="tab">Completed</a></li>
  <li ><a href="#transit" data-toggle="tab">In Transit</a></li>
  <li ><a href="#all" data-toggle="tab">All</a></li>
</ul>

bookrequests/templates/bookrequests/borrowed_index.html
{% extends "users_base.html" %}
{% load request_extras %}
{% load staticfiles %}

<script type="text/javascript" src="{% static "bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "bookrequests/borrowed-index.js" %}"></script>

{% block content %}

{# tabs for grouping requests based on status #}
{% include "_request_tabs.html" %}

{# content of each tab #}
<div class="tab-content list-group">
	<div class="tab-pane active" id="pending">
		{% for r in requests|pending %}
			<div class="list-group-item">
				{% show_request_borrower r %}
			</div>
		{% empty %}
			<div class="alert">You do not have any borrowed books right now</div>
		{% endfor %}
	</div>
	<div class="tab-pane" id="all">
		{% for r in requests %}
			<div class="list-group-item">
				{% show_request_borrower r %}
			</div>
		{% empty %}
			<div class="alert">You have not borrowed any books yet. Try searching for a book!</div>
		{% endfor %}
	</div>
	<div class="tab-pane" id="completed">
		{% for r in requests|completed %}
			<div class="list-group-item">
				{% show_request_borrower r %}
			</div>
		{% empty %}
			<div class="alert">You have not returned any borrowed books yet</div>
		{% endfor %}
	</div>
	<div class="tab-pane" id="transit">
		{% for r in requests|intransit %}
			<div class="list-group-item">
				{% show_request_borrower r %}
			</div>
		{% empty %}
			<div class="alert">None of your requested books is with a courier</div>
		{% endfor %}
	</div>
</div>

	

{% endblock content %}

bookrequests/templates/bookrequests/lent_index.html
{% extends "users_base.html" %}
{% load request_extras %}

{% block content %}

{% include "_request_tabs.html" %}

<div class="tab-content list-group">
	<div class="tab-pane active" id="pending">
		{% for r in requests|pending %}
			<div class="list-group-item">
				{% show_request_owner r %}
			</div>
		{% empty %}
			<div class="alert">
				You do not have any pending requests. 
				Try
				 <a href="{% url 'users:books:add_book' %}">adding</a>
				more books?	
			</div>
			
		{% endfor %}
	</div>
	<div class="tab-pane" id="all">
		{% for r in requests %}
			<div class="list-group-item">
				{% show_request_owner r %}
			</div>
		{% empty %}
			<div class="alert">
				You have not lent out any of your books. 
				Try
				 <a href="{% url 'users:books:add_book' %}">adding</a>
				more books?
			</div>
		{% endfor %}
	</div>
	<div class="tab-pane" id="completed">
		{% for r in requests|completed %}
			<div class="list-group-item">
				{% show_request_owner r %}
			</div>
		{% empty %}
			<div class="alert">You have not completed any book requests</div>
			
		{% endfor %}
	</div>
	<div class="tab-pane" id="transit">
		{% for r in requests|intransit %}
			<div class="list-group-item">
				{% show_request_owner r %}
			</div>
		{% empty %}
			<div class="alert">None of your books is with a courier</div>	
			
		{% endfor %}
	</div>

</div>

{% endblock content %}

bookrequests/templates/bookrequests/request_borrower.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" 
href="{% static "css/request-borrower.css" %}">

<script type="text/javascript" src="{% static "js/request-borrower.js" %}"></script>

<div>
	{{ message }}

	{% if return_button %}
			<a href="{% url 'users:requests:return' request_id %}" 
			class="return-button">
				<span class="glyphicon glyphicon-check"></span>
			</a>
	{% endif %}
</div>

bookrequests/templates/bookrequests/request_courier.html
{% load staticfiles %}


<link rel="stylesheet" type="text/css" 
href="{% static "css/request-courier.css" %}">

<script type="text/javascript" src="{% static "js/request-courier.js" %}"></script>
<div>
	{{ message }}

	{% if confirm_button %}
		<a href="{% url 'courier:advance' req_id %}" 
		class="done-button">
			<span class="glyphicon glyphicon-ok"></span>
		</a>	
	{% endif %}
	
</div>

bookrequests/templates/bookrequests/request_owner.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" 
href="{% static "css/request-owner.css" %}">

<div>
	{{ message }}

	{% if accept_buttons %}
		<span class="accept-buttons">
			<a href="{% url 'users:requests:accept' request_id %}" 
			class="accept-button">
				<span class="glyphicon glyphicon-ok"></span>
			</a>

			<a href="{% url 'users:requests:reject' request_id %}"
			class="reject-button">
				<span class="glyphicon glyphicon-remove"></span>
			</a>
		</span>
	{% endif %}
</div>