books/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from books import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^add_book/$', views.add_book, name='add_book'),
	url(r'^edit_book/(?P<book_id>\d+)/$', views.edit_book, name='edit_book'),
	url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
	url(r'^search/$', views.search, name='search'),
	url(r'^make_request/(?P<id>\d+)/$', views.make_request, name='make_request'),
)

urlpatterns += staticfiles_urlpatterns()

bookzilla/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from bookzilla import views

urlpatterns = patterns('',
	# index page
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^admin/', include(admin.site.urls)),
    
    # the users module
    url(r'^users/', include('users.urls', namespace='users')),
    # courier module
    url(r'^courier/', include('courier.urls', namespace='courier')),
)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from users import views

import notifications

urlpatterns = patterns('',
	url(r'^home/$', views.home, name='home'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),		

	# books module
	url(r'^books/', include('books.urls', namespace='books')),
	# bookrequests module
	url(r'^requests/', include('bookrequests.urls', namespace='requests')),
	# notifications
    url('^inbox/notifications/', include(notifications.urls)),
)

urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends "base.html" %}

{% block content %}

This is the about page. Needs to be updated.

{% endblock content %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookzilla</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">
    {# <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}"> #}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Bookzilla</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'users:register' %}">Signup</a></li>
            <li><a href="{% url 'users:login' %}">Login</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}">{{ msg }}</div>  
          {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

Chandan - cy@test.com <br>
Ananth - ant@test.com

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">

<img src="{% static "img/Bookzilla.png" %}" id="main-logo">
{% endblock content %}